import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";

const Home: NextPage = () => {
  // check if input file has value to show preview
  const [isShowPreview, setIsShowPreview] = useState<boolean>(false);
  // check if input file has value useEffect to get preview data
  const [selectedImg, setSelectedImg] = useState<File>();
  // get preview data
  const [preview, setPreview] = useState<string>();

  // to clear data of input or open dialog if user click edit icon
  const inputImageRef = useRef(null);

  useEffect(() => {
    if (selectedImg) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setPreview(reader.result as string);
        setIsShowPreview(true);
      };
      reader.readAsDataURL(selectedImg);
    } else {
      setPreview(undefined);
    }
  }, [selectedImg]);

  // get file and set to selectedImg when input changed
  const inputFileChange = (event: any) => {
    const file = event.target.files[0];
    if (file && file.type.substr(0, 5) === "image") {
      setSelectedImg(file);
    } else {
      setSelectedImg(undefined);
    }
  };

  // Handling the edit icon
  const editSelectedImg = () => {
    setSelectedImg(undefined);
    setPreview(undefined);
    setIsShowPreview(false);
    inputImageRef.current.value = "";
    inputImageRef?.current.click();
  };

  // Handling the delete icon
  const removeSelectedImg = () => {
    setSelectedImg(undefined);
    setPreview(undefined);
    setIsShowPreview(false);
    inputImageRef.current.value = "";
  };

  return (
    <>
      <Head>
        <title>Image Preview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
          integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>

      <main className="container">
        <h1 className="text-center">
          Image preview {isShowPreview ? "Show" : "Hide"}
        </h1>
        <section className="d-flex justify-content-center align-items-center">
          <div className="img-uploader">
            <div className={`input-uploader ${!isShowPreview ? "" : "d-none"}`}>
              <input
                type="file"
                name="thumbnail"
                title="Thumbnail"
                onChange={inputFileChange}
                ref={inputImageRef}
              />
              <div className="label-uploader d-flex flex-column justify-content-center align-items-center">
                <label htmlFor="">Choose Image File</label>
                <i className="fa-solid fa-cloud-arrow-up"></i>
              </div>
            </div>
            <div
              className={`img-preview d-flex flex-column justify-content-between align-items-center ${
                isShowPreview ? "" : "d-none"
              }`}
            >
              <div className="preview-img">
                <img src={preview} alt="Preview" />
              </div>
              <div className="preview-controls d-flex justify-content-center align-items-center">
                <i className="fa-solid fa-edit" onClick={editSelectedImg}></i>
                <i
                  className="fa-solid fa-trash"
                  onClick={removeSelectedImg}
                ></i>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
