import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

const Home: NextPage = () => {
  const [isShowPreview, setIsShowPreview] = useState<boolean>(true);
  const [selectedImg, setSelectedImg] = useState<File>();
  const [preview, setPreview] = useState<string>();

  return (
    <>
      <Head>
        <title>Image Preview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
          integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>

      <main className="container">
        <h1 className="text-center">Image preview</h1>
        <section className="d-flex justify-content-center align-items-center">
          <div className="img-uploader">
            <div className={`input-uploader ${!isShowPreview ? "d-none" : ""}`}>
              <input type="file" name="thumbnail" title="Thumbnail" />
              <div className="label-uploader d-flex flex-column justify-content-center align-items-center">
                <label htmlFor="">Choose Image File</label>
                <i className="fa-solid fa-cloud-arrow-up"></i>
              </div>
            </div>
            <div
              className={`img-preview d-flex flex-column justify-content-between align-items-center ${
                isShowPreview ? "d-none" : ""
              }`}
            >
              <div className="preview-img">
                <img src="/images/img1.jpg" alt="Preview" />
              </div>
              <div className="preview-controls d-flex justify-content-center align-items-center">
                <i className="fa-solid fa-edit"></i>
                <i className="fa-solid fa-trash"></i>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
